/*
 * generated by Xtext 2.29.0
 */
package se.gu.cse.idxse.bomi.text.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import se.gu.cse.idxse.bomi.text.parser.antlr.internal.InternalBomiParser;
import se.gu.cse.idxse.bomi.text.services.BomiGrammarAccess;

public class BomiParser extends AbstractAntlrParser {

	@Inject
	private BomiGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBomiParser createParser(XtextTokenStream stream) {
		return new InternalBomiParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BOMIModel";
	}

	public BomiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BomiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
