/*
 * generated by Xtext 2.28.0
 */
package se.gu.cse.idxse.bomi.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BomiAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("se/gu/cse/idxse/bomi/text/parser/antlr/internal/InternalBomi.tokens");
	}
}
