/*
 * generated by Xtext 2.27.0
 */
package se.gu.cse.idxse.bomi.text;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BomiStandaloneSetup extends BomiStandaloneSetupGenerated {

	public static void doSetup() {
		new BomiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
