/*
 * generated by Xtext 2.27.0
 */
package se.gu.cse.idxse.bomi.text;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BomiRuntimeModule extends AbstractBomiRuntimeModule {
}
