/*
 * generated by Xtext 2.27.0
 */
package se.gu.cse.idxse.bomi.text.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class BomiProposalProvider extends AbstractBomiProposalProvider {
}
