/*
 * generated by Xtext 2.27.0
 */
package se.gu.cse.idxse.bomi.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BomiUiModule extends AbstractBomiUiModule {

	public BomiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
