/*
 * generated by Xtext 2.28.0
 */
package se.gu.cse.idxse.bomi.text.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBomiScopeProvider extends DelegatingScopeProvider {
}
