/*
 * generated by Xtext 2.28.0
 */
package se.gu.cse.idxse.bomi.text.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import se.gu.cse.idxse.bomi.text.ide.contentassist.antlr.internal.InternalBomiParser;
import se.gu.cse.idxse.bomi.text.services.BomiGrammarAccess;

public class BomiParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BomiGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BomiGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getHighLowAccess().getAlternatives(), "rule__HighLow__Alternatives");
			builder.put(grammarAccess.getBOSuperTypesAccess().getAlternatives(), "rule__BOSuperTypes__Alternatives");
			builder.put(grammarAccess.getLifecycleStageAccess().getAlternatives(), "rule__LifecycleStage__Alternatives");
			builder.put(grammarAccess.getMITypeAccess().getAlternatives(), "rule__MIType__Alternatives");
			builder.put(grammarAccess.getDriverTypesAccess().getAlternatives(), "rule__DriverTypes__Alternatives");
			builder.put(grammarAccess.getDistanceTypesAccess().getAlternatives(), "rule__DistanceTypes__Alternatives");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup(), "rule__BOMIModel__Group__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_1(), "rule__BOMIModel__Group_1__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_1_3(), "rule__BOMIModel__Group_1_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_2(), "rule__BOMIModel__Group_2__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_2_3(), "rule__BOMIModel__Group_2_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_3(), "rule__BOMIModel__Group_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_3_3(), "rule__BOMIModel__Group_3_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_4(), "rule__BOMIModel__Group_4__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_4_3(), "rule__BOMIModel__Group_4_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_5(), "rule__BOMIModel__Group_5__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_5_3(), "rule__BOMIModel__Group_5_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_6(), "rule__BOMIModel__Group_6__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_6_1(), "rule__BOMIModel__Group_6_1__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_7(), "rule__BOMIModel__Group_7__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_7_1(), "rule__BOMIModel__Group_7_1__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_8(), "rule__BOMIModel__Group_8__0");
			builder.put(grammarAccess.getBOMIModelAccess().getGroup_8_1(), "rule__BOMIModel__Group_8_1__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup(), "rule__BoundaryObject__Group__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_4(), "rule__BoundaryObject__Group_4__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_5(), "rule__BoundaryObject__Group_5__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_6(), "rule__BoundaryObject__Group_6__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_7(), "rule__BoundaryObject__Group_7__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_8(), "rule__BoundaryObject__Group_8__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_9(), "rule__BoundaryObject__Group_9__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_10(), "rule__BoundaryObject__Group_10__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_11(), "rule__BoundaryObject__Group_11__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_12(), "rule__BoundaryObject__Group_12__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_13(), "rule__BoundaryObject__Group_13__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_14(), "rule__BoundaryObject__Group_14__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_15(), "rule__BoundaryObject__Group_15__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_16(), "rule__BoundaryObject__Group_16__0");
			builder.put(grammarAccess.getBoundaryObjectAccess().getGroup_17(), "rule__BoundaryObject__Group_17__0");
			builder.put(grammarAccess.getMethodologicalIslandAccess().getGroup(), "rule__MethodologicalIsland__Group__0");
			builder.put(grammarAccess.getMethodologicalIslandAccess().getGroup_4(), "rule__MethodologicalIsland__Group_4__0");
			builder.put(grammarAccess.getGovernanceTeamAccess().getGroup(), "rule__GovernanceTeam__Group__0");
			builder.put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
			builder.put(grammarAccess.getRoleAccess().getGroup_4(), "rule__Role__Group_4__0");
			builder.put(grammarAccess.getRoleAccess().getGroup_4_3(), "rule__Role__Group_4_3__0");
			builder.put(grammarAccess.getRoleAccess().getGroup_5(), "rule__Role__Group_5__0");
			builder.put(grammarAccess.getRoleAccess().getGroup_5_3(), "rule__Role__Group_5_3__0");
			builder.put(grammarAccess.getDriverAccess().getGroup(), "rule__Driver__Group__0");
			builder.put(grammarAccess.getDriverAccess().getGroup_4(), "rule__Driver__Group_4__0");
			builder.put(grammarAccess.getDriverAccess().getGroup_5(), "rule__Driver__Group_5__0");
			builder.put(grammarAccess.getDriverAccess().getGroup_6(), "rule__Driver__Group_6__0");
			builder.put(grammarAccess.getDriverAccess().getGroup_7(), "rule__Driver__Group_7__0");
			builder.put(grammarAccess.getDriverAccess().getGroup_7_3(), "rule__Driver__Group_7_3__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup(), "rule__BOMICoordination__Group__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_4(), "rule__BOMICoordination__Group_4__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_5(), "rule__BOMICoordination__Group_5__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_6(), "rule__BOMICoordination__Group_6__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_7(), "rule__BOMICoordination__Group_7__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_8(), "rule__BOMICoordination__Group_8__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_9(), "rule__BOMICoordination__Group_9__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_9_3(), "rule__BOMICoordination__Group_9_3__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_10(), "rule__BOMICoordination__Group_10__0");
			builder.put(grammarAccess.getBOMICoordinationAccess().getGroup_10_3(), "rule__BOMICoordination__Group_10_3__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup(), "rule__BORoleInteraction__Group__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_4(), "rule__BORoleInteraction__Group_4__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_5(), "rule__BORoleInteraction__Group_5__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_6(), "rule__BORoleInteraction__Group_6__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_7(), "rule__BORoleInteraction__Group_7__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_8(), "rule__BORoleInteraction__Group_8__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_9(), "rule__BORoleInteraction__Group_9__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_9_3(), "rule__BORoleInteraction__Group_9_3__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_10(), "rule__BORoleInteraction__Group_10__0");
			builder.put(grammarAccess.getBORoleInteractionAccess().getGroup_10_3(), "rule__BORoleInteraction__Group_10_3__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup(), "rule__BOTeamGovernance__Group__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_4(), "rule__BOTeamGovernance__Group_4__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_5(), "rule__BOTeamGovernance__Group_5__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_6(), "rule__BOTeamGovernance__Group_6__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_7(), "rule__BOTeamGovernance__Group_7__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_7_3(), "rule__BOTeamGovernance__Group_7_3__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_8(), "rule__BOTeamGovernance__Group_8__0");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGroup_8_3(), "rule__BOTeamGovernance__Group_8_3__0");
			builder.put(grammarAccess.getBOMIModelAccess().getBoundaryObjectsAssignment_1_2(), "rule__BOMIModel__BoundaryObjectsAssignment_1_2");
			builder.put(grammarAccess.getBOMIModelAccess().getBoundaryObjectsAssignment_1_3_1(), "rule__BOMIModel__BoundaryObjectsAssignment_1_3_1");
			builder.put(grammarAccess.getBOMIModelAccess().getMethodologicalIslandsAssignment_2_2(), "rule__BOMIModel__MethodologicalIslandsAssignment_2_2");
			builder.put(grammarAccess.getBOMIModelAccess().getMethodologicalIslandsAssignment_2_3_1(), "rule__BOMIModel__MethodologicalIslandsAssignment_2_3_1");
			builder.put(grammarAccess.getBOMIModelAccess().getGovernanceTeamsAssignment_3_2(), "rule__BOMIModel__GovernanceTeamsAssignment_3_2");
			builder.put(grammarAccess.getBOMIModelAccess().getGovernanceTeamsAssignment_3_3_1(), "rule__BOMIModel__GovernanceTeamsAssignment_3_3_1");
			builder.put(grammarAccess.getBOMIModelAccess().getRolesAssignment_4_2(), "rule__BOMIModel__RolesAssignment_4_2");
			builder.put(grammarAccess.getBOMIModelAccess().getRolesAssignment_4_3_1(), "rule__BOMIModel__RolesAssignment_4_3_1");
			builder.put(grammarAccess.getBOMIModelAccess().getDriversAssignment_5_2(), "rule__BOMIModel__DriversAssignment_5_2");
			builder.put(grammarAccess.getBOMIModelAccess().getDriversAssignment_5_3_1(), "rule__BOMIModel__DriversAssignment_5_3_1");
			builder.put(grammarAccess.getBOMIModelAccess().getBoMiCoordinationsAssignment_6_0(), "rule__BOMIModel__BoMiCoordinationsAssignment_6_0");
			builder.put(grammarAccess.getBOMIModelAccess().getBoMiCoordinationsAssignment_6_1_1(), "rule__BOMIModel__BoMiCoordinationsAssignment_6_1_1");
			builder.put(grammarAccess.getBOMIModelAccess().getBoRoleInteractionsAssignment_7_0(), "rule__BOMIModel__BoRoleInteractionsAssignment_7_0");
			builder.put(grammarAccess.getBOMIModelAccess().getBoRoleInteractionsAssignment_7_1_1(), "rule__BOMIModel__BoRoleInteractionsAssignment_7_1_1");
			builder.put(grammarAccess.getBOMIModelAccess().getBoTeamGovernancesAssignment_8_0(), "rule__BOMIModel__BoTeamGovernancesAssignment_8_0");
			builder.put(grammarAccess.getBOMIModelAccess().getBoTeamGovernancesAssignment_8_1_1(), "rule__BOMIModel__BoTeamGovernancesAssignment_8_1_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getNameAssignment_2(), "rule__BoundaryObject__NameAssignment_2");
			builder.put(grammarAccess.getBoundaryObjectAccess().getSuperTypeAssignment_4_1(), "rule__BoundaryObject__SuperTypeAssignment_4_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getPurposeAssignment_5_1(), "rule__BoundaryObject__PurposeAssignment_5_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getLevelOfDetailAssignment_6_1(), "rule__BoundaryObject__LevelOfDetailAssignment_6_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getFrequencyOfChangeAssignment_7_1(), "rule__BoundaryObject__FrequencyOfChangeAssignment_7_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getModularityAssignment_8_1(), "rule__BoundaryObject__ModularityAssignment_8_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getMaintainabilityAssignment_9_1(), "rule__BoundaryObject__MaintainabilityAssignment_9_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getPrescriptiveAssignment_10_1(), "rule__BoundaryObject__PrescriptiveAssignment_10_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getLifecycleStageAssignment_11_1(), "rule__BoundaryObject__LifecycleStageAssignment_11_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getRepresentationFormatAssignment_12_1(), "rule__BoundaryObject__RepresentationFormatAssignment_12_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getToolingAssignment_13_1(), "rule__BoundaryObject__ToolingAssignment_13_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getVersioningAssignment_14_1(), "rule__BoundaryObject__VersioningAssignment_14_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getUpToDateAssignment_15_1(), "rule__BoundaryObject__UpToDateAssignment_15_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getInternalConsistencyAssignment_16_1(), "rule__BoundaryObject__InternalConsistencyAssignment_16_1");
			builder.put(grammarAccess.getBoundaryObjectAccess().getExternalConsistencyAssignment_17_1(), "rule__BoundaryObject__ExternalConsistencyAssignment_17_1");
			builder.put(grammarAccess.getMethodologicalIslandAccess().getNameAssignment_2(), "rule__MethodologicalIsland__NameAssignment_2");
			builder.put(grammarAccess.getMethodologicalIslandAccess().getTypeAssignment_4_1(), "rule__MethodologicalIsland__TypeAssignment_4_1");
			builder.put(grammarAccess.getGovernanceTeamAccess().getNameAssignment_2(), "rule__GovernanceTeam__NameAssignment_2");
			builder.put(grammarAccess.getRoleAccess().getNameAssignment_2(), "rule__Role__NameAssignment_2");
			builder.put(grammarAccess.getRoleAccess().getPartOfGovernanceTeamsAssignment_4_2(), "rule__Role__PartOfGovernanceTeamsAssignment_4_2");
			builder.put(grammarAccess.getRoleAccess().getPartOfGovernanceTeamsAssignment_4_3_1(), "rule__Role__PartOfGovernanceTeamsAssignment_4_3_1");
			builder.put(grammarAccess.getRoleAccess().getPartOfMIsAssignment_5_2(), "rule__Role__PartOfMIsAssignment_5_2");
			builder.put(grammarAccess.getRoleAccess().getPartOfMIsAssignment_5_3_1(), "rule__Role__PartOfMIsAssignment_5_3_1");
			builder.put(grammarAccess.getDriverAccess().getNameAssignment_2(), "rule__Driver__NameAssignment_2");
			builder.put(grammarAccess.getDriverAccess().getDriverTypeAssignment_4_1(), "rule__Driver__DriverTypeAssignment_4_1");
			builder.put(grammarAccess.getDriverAccess().getDistanceTypeAssignment_5_1(), "rule__Driver__DistanceTypeAssignment_5_1");
			builder.put(grammarAccess.getDriverAccess().getDistanceSizeAssignment_6_1(), "rule__Driver__DistanceSizeAssignment_6_1");
			builder.put(grammarAccess.getDriverAccess().getDrivesMIsAssignment_7_2(), "rule__Driver__DrivesMIsAssignment_7_2");
			builder.put(grammarAccess.getDriverAccess().getDrivesMIsAssignment_7_3_1(), "rule__Driver__DrivesMIsAssignment_7_3_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getNameAssignment_2(), "rule__BOMICoordination__NameAssignment_2");
			builder.put(grammarAccess.getBOMICoordinationAccess().getPurposeAssignment_4_1(), "rule__BOMICoordination__PurposeAssignment_4_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getAccessabilityAssignment_5_1(), "rule__BOMICoordination__AccessabilityAssignment_5_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getStabilityAssignment_6_1(), "rule__BOMICoordination__StabilityAssignment_6_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getCriticalityAssignment_7_1(), "rule__BOMICoordination__CriticalityAssignment_7_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getFitForPurposeAssignment_8_1(), "rule__BOMICoordination__FitForPurposeAssignment_8_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getBoundaryObjectsAssignment_9_2(), "rule__BOMICoordination__BoundaryObjectsAssignment_9_2");
			builder.put(grammarAccess.getBOMICoordinationAccess().getBoundaryObjectsAssignment_9_3_1(), "rule__BOMICoordination__BoundaryObjectsAssignment_9_3_1");
			builder.put(grammarAccess.getBOMICoordinationAccess().getMethodologicalIslandsAssignment_10_2(), "rule__BOMICoordination__MethodologicalIslandsAssignment_10_2");
			builder.put(grammarAccess.getBOMICoordinationAccess().getMethodologicalIslandsAssignment_10_3_1(), "rule__BOMICoordination__MethodologicalIslandsAssignment_10_3_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getNameAssignment_2(), "rule__BORoleInteraction__NameAssignment_2");
			builder.put(grammarAccess.getBORoleInteractionAccess().getPurposeAssignment_4_1(), "rule__BORoleInteraction__PurposeAssignment_4_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getAccessabilityAssignment_5_1(), "rule__BORoleInteraction__AccessabilityAssignment_5_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getStabilityAssignment_6_1(), "rule__BORoleInteraction__StabilityAssignment_6_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getCriticalityAssignment_7_1(), "rule__BORoleInteraction__CriticalityAssignment_7_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getFitForPurposeAssignment_8_1(), "rule__BORoleInteraction__FitForPurposeAssignment_8_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getBoundaryObjectsAssignment_9_2(), "rule__BORoleInteraction__BoundaryObjectsAssignment_9_2");
			builder.put(grammarAccess.getBORoleInteractionAccess().getBoundaryObjectsAssignment_9_3_1(), "rule__BORoleInteraction__BoundaryObjectsAssignment_9_3_1");
			builder.put(grammarAccess.getBORoleInteractionAccess().getRolesAssignment_10_2(), "rule__BORoleInteraction__RolesAssignment_10_2");
			builder.put(grammarAccess.getBORoleInteractionAccess().getRolesAssignment_10_3_1(), "rule__BORoleInteraction__RolesAssignment_10_3_1");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getNameAssignment_2(), "rule__BOTeamGovernance__NameAssignment_2");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getPurposeAssignment_4_1(), "rule__BOTeamGovernance__PurposeAssignment_4_1");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getCoordinationMechanismAssignment_5_1(), "rule__BOTeamGovernance__CoordinationMechanismAssignment_5_1");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getFrequencyOfCoordinationAssignment_6_1(), "rule__BOTeamGovernance__FrequencyOfCoordinationAssignment_6_1");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGovernanceTeamsAssignment_7_2(), "rule__BOTeamGovernance__GovernanceTeamsAssignment_7_2");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getGovernanceTeamsAssignment_7_3_1(), "rule__BOTeamGovernance__GovernanceTeamsAssignment_7_3_1");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getBoundaryObjectsAssignment_8_2(), "rule__BOTeamGovernance__BoundaryObjectsAssignment_8_2");
			builder.put(grammarAccess.getBOTeamGovernanceAccess().getBoundaryObjectsAssignment_8_3_1(), "rule__BOTeamGovernance__BoundaryObjectsAssignment_8_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BomiGrammarAccess grammarAccess;

	@Override
	protected InternalBomiParser createParser() {
		InternalBomiParser result = new InternalBomiParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BomiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BomiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
